version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install && cd client && npm install
            - run: npm test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Deployment
          command: echo "Deploy this"

workflows:
  build-and-test:
    jobs:
      - build-and-test
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
      - deploy
      
    